program: train_dgcnn.py
method: bayes
project: modelnet40_experiments
metric:
  name: val_loss
  goal: minimize
parameters:
  lr:
    min: 0.0001
    max: 0.001
  optimizer:
    values: [adamw, sgd]
  dropout:
    values: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5]
  gradient_clip_val:
    values: [0, 2]
  epochs:
    value: 100
  warm_up:
    value: 10