program: train_dgcnn.py
method: random
project: modelnet40_experiments
metric:
  name: val_acc
  goal: maximize
parameters:
  lr:
    distribution: uniform
    min: 0.0001
    max: 0.004
  optimizer:
    values: ["adamw", "sgd"]
  dropout:
    values: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5]
  gradient_clip_val:
    distribution: int_uniform
    max: 4
    min: 0
  epochs:
    value: 100
  warm_up:
    value: 10