program: train_pointnet.py
method: grid
project: modelnet40_experiments
metric:
  name: val_acc
  goal: maximize
parameters:
  lr:
    values: [ 0.1, 0.01, 0.001 ]
  optimizer:
    values: [ "sgd", "adamw",  "adam" ]
  gradient_clip_val:
    values: [ 0, 2 ]
  dropout:
    values: [ 0.3, 0.4, 0.5 ]
  epochs:
    value: 100
  warm_up:
    value: 10